"""reconciliation reports table

Revision ID: 57b34aed3928
Revises: ab10ded442e0
Create Date: 2026-08-18 00:25:58.570589

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "57b34aed3928"
down_revision: str | None = "ab10ded442e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliation_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payment_intent_id", sa.UUID(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.Column("internal_status", sa.String(), nullable=False),
        sa.Column("provider_status", sa.String(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "result IN ('MATCHED', 'RESOLVED_SUCCEEDED', 'RESOLVED_FAILED', 'STILL_UNKNOWN', 'MISSING_PROVIDER_TRANSACTION', 'MISSING_INTERNAL_TRANSACTION', 'AMOUNT_MISMATCH', 'CURRENCY_MISMATCH')",
            name="ck_reconciliation_reports_result",
        ),
        sa.ForeignKeyConstraint(
            ["payment_intent_id"],
            ["payment_intents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_reconciliation_reports_created_at", "reconciliation_reports", ["created_at"], unique=False
    )
    op.create_index(
        "ix_reconciliation_reports_payment_intent_id",
        "reconciliation_reports",
        ["payment_intent_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reconciliation_reports_payment_intent_id", table_name="reconciliation_reports")
    op.drop_index("ix_reconciliation_reports_created_at", table_name="reconciliation_reports")
    op.drop_table("reconciliation_reports")
    # ### end Alembic commands ###
